using UnityEngine;

namespace Game.AnimationLayers
{
    public class AniLayerDemo : MonoBehaviour
    {
		// Generate integers by hashing strings
		private static readonly int aniMoveSpeed = Animator.StringToHash("MoveSpeed");
		private static readonly int aniIsCarrying = Animator.StringToHash("IsCarrying");

		[Header("Animation")]
		[SerializeField] private Animator animator;

		[Header("Movement")]
		[SerializeField] private float walkSpeed;
		[SerializeField] private float runSpeed;
		[SerializeField] private float acceleration;
		private float velocity;

		[Header("Input")]
		private PlayerControls controls;

		[Header("Equipment")]
		private bool isCarrying;

		private void Awake()
		{
			controls = new PlayerControls();	// PlayerControls input generated by Input
		}

		private void OnEnable()
		{
			controls.Player.Enable();
		}

		private void OnDisable()
		{
			controls.Player.Disable();
		}

		private void Update()
		{
			// Get move speed
			float move = controls.Player.Move.ReadValue<Vector2>().x;
			bool sprint = controls.Player.Sprint.IsPressed();
			move *= (sprint ? runSpeed : walkSpeed);

			// Move

			velocity = Mathf.MoveTowards(velocity, move, acceleration * Time.deltaTime);
			transform.position += new Vector3(0f, 0f, velocity * Time.deltaTime);

			// Move speed animation
			animator.SetFloat(aniMoveSpeed, velocity / runSpeed); //Send speed as percetage of max for blendtree

			// Check collisions
			if (!isCarrying)
			{
				Collider[] col = Physics.OverlapSphere(transform.position, 0.5f);
				if(col.Length > 0)
				{
					isCarrying = true;
					col[0].gameObject.SetActive(false);
					animator.SetBool(aniIsCarrying, true);
				}
			}
		}
	}
}
